account = {
    'Account Name': 'Test Account 1',
    'Account Number': 'Account Number Text',
    'Account Site': 'Account Site Text',
    'Type': 'Pending',
    'Industry': 'Apparel',
    'Annual Revenue': '1,000,000',
    'Match Billing Address': 'true',
    'Rating': 'Warm',
    'Phone': '6028675309',
    'Fax': '6028675310',
    'Website': 'https://website.com',
    'Ticker Symbol': 'TS',
    'Ownership': 'Private',
    'Employees': '33',
    'SIC Code': 'SIC',
}
